### PR TITLE
Graceful Javadoc remapping

### LINKED ISSUE #23: Javadoc remapping fails hard on an unresolved {@link}
Javadocs don't need to build for a program to compile, so preferably they'd just get passed over if they can't be remapped.

[error](https://pastebin.com/vHYX2qX7) (gradle exception stripped)
[sample of crashing code](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/64d4a9be25924ca7e064df67f692ead8cf492d5c/src/main/java/com/mcmoddev/golems/entity/base/GolemMultiColorized.java#L342)

### PR DESCRIPTION
**Pull request by ramidzkh**
Looks like invalid members don't cause a crash

### CODE REVIEW

**Comment by phase** [comment]
Is there any case where you would want the two classpath check flags to have different values? IIRC, fabric is already using the graceful classpath check, so reusing that flag would make things simpler.

**Comment by jamierocks** [comment]
Depending on what Java version you compile with (and or what flags you use), Javadocs aren't exactly strict.

**Review by phase — APPROVED** [review]

**Comment by ramidzkh** [comment]
All I can think of is making `gracefulJavadocClasspathChecks` true by default, as correct Javadocs aren't required for building

**Comment by jamierocks** [comment]
Merged with https://github.com/CadixDev/Mercury/commit/76d393ef9453e124865092b5ce4baf8bddbfa31c.

I'll think over changing the default :)

**Pull request closed without merging**
