### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by 116s**
- Update Gradle from 6.0.1 to 6.8.2
  - Enable build cache. 
  - Add sha256sum check.

- Update lorenz from 0.5.2 to 0.5.7.
- Update uk.jamierocks.propatcher from 1.3.1 to 1.3.2.
- Update jupiter from 5.6.0 to 5.7.0 ([changelog](https://junit.org/junit5/docs/current/release-notes/index.html#release-notes))

### CODE REVIEW

**Comment by jamierocks** [comment]
Thank you, I was planning to update the JDT atleast in the coming days - thanks for saving me the time :)

@demonwav could you review the Gradle changes for me?

I'll double check that our JDT patches didn't need any changes made after work tomorrow, and then we can get this merged ASAP :)

**Comment by 116s** [comment]
Bump

**Comment by 116s** [comment]
Rebased and updated another dependency to the latest version. @jamierocks

**Comment by jamierocks** [comment]
Thanks for the contribution! Apologies it took so long to get around to merging it.

Since the build cache is still experimental and that its not something we use through the Cadix software yet, I've decided not to proceed with merging that.

Since GitHub isn't smart enough to identify, this PR was merged with https://github.com/CadixDev/Mercury/commit/1a290ea60cd7ac7c0d42ec023448f0c785b3c225 :)

**Pull request closed without merging**
